# Generated by Django 3.2.6 on 2021-08-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('age', models.IntegerField(default=-1)),
                ('profile_photo', models.URLField(default=None)),
                ('description', models.CharField(default='', max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
